#!/bin/bash

MTARGET=~/android/modules
MTARGET_LIVE=~/android/modules_live


for x in `find . | grep \.ko$` ; do
	echo "> $x"
	cp $x $MTARGET
	cp $x $MTARGET_LIVE
done

cp ./arch/arm/boot/zImage $MTARGET/../kernel
cp ./arch/arm/boot/zImage $MTARGET_LIVE/../kernel

ls -l $MTARGET
ls -l $MTARGET/../kernel
